### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by asymmetric**
* changes order of frob params to follow dss
* makes some params more explicit
* adds (helpful?) comments

### CODE REVIEW

**Comment by levity** [comment]
want to create a corresponding PR for makerdao/dss-proxy-actions?

**Comment by gbalabasquer** [comment]
Let's discuss the cdp position parameter next week. Do not remember why I had put it before, I had some reasoning that I need to remember. :P

**Comment by asymmetric** [comment]
@gbalabasquer bump :)

**Comment by gbalabasquer** [comment]
Let's keep it on hold until we finish defining if we will be limiting the `urn` to a specific `ilk`. As if we do it, we don't need `ilk` at all in `frob`.

**Comment by gbalabasquer** [comment]
Closing this as well. The PR got outdated as we are not passing `ilk` anymore in `frob`.

**Pull request closed without merging**
